

SELECT
    O_ORDERDATE,
    SUM(O_TOTALPRICE) OVER (ORDER BY O_ORDERDATE ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_sum
FROM
    "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS"
